Update

diff --git a/.github/workflows/test-code.yml b/.github/workflows/test-code.yml
--- a/.github/workflows/test-code.yml
+++ b/.github/workflows/test-code.yml
@@ -149,8 +149,34 @@ jobs:
           exit 1
       - name: Build supergraph
         working-directory: src
+        run: rover supergraph compose --config ./federation-supergraph-config.yaml --elv2-license=accept > supergraph.graphql
+      - name: Print supergraph
+        working-directory: src
+        run: cat supergraph.graphql
+      - name: Validate supergraph
+        working-directory: src
+        run: rover supergraph validate --config ./federation-supergraph-config.yaml --schema supergraph.graphql
+      - name: Download router
+        working-directory: src
+        run: curl -sSL https://router.apollo.dev/download/nix/latest | sh
+      - name: Start router
+        working-directory: src
+        run: ./router --supergraph supergraph.graphql --port 5600 &
+      - name: Wait for router to spin up
         run: |
-          rover supergraph compose --config ./federation-supergraph-config.yaml --elv2-license=accept
+          for i in {1..60}
+          do
+            echo "Request $i to the URL..."
+            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5600)
+            if [ $response -eq 200 ]; then
+              echo "Received 200 response, step completed."
+              exit 0
+            fi
+            echo "Did not receive a 200 response, sleeping for 0.5 second..."
+            sleep 0.5
+          done
+          echo "Timed out after 30 seconds, step failed."
+          exit 1
   buildcheck:
     needs:
       - test
