Fix CI workflows (#4117)
* Fix GitHub Actions

* update

* update target framework for federation samples

* Run .NET Core 3.1 tests only on Windows

diff --git a/.github/workflows/test-code.yml b/.github/workflows/test-code.yml
--- a/.github/workflows/test-code.yml
+++ b/.github/workflows/test-code.yml
@@ -138,6 +138,7 @@ jobs:
         run: sudo apt-get install -y jq
       - name: Wait for Sample1 to spin up
         run: |
+          set +e  # disable exit on error
           for i in {1..60}
           do
             echo "Request $i to the URL..."
@@ -149,10 +150,12 @@ jobs:
             echo "Did not receive a 200 response, sleeping for 0.5 second..."
             sleep 0.5
           done
+          set -e  # enable exit on error
           echo "Timed out after 30 seconds, step failed."
           exit 1
       - name: Wait for Sample2 to spin up
         run: |
+          set +e  # disable exit on error
           for i in {1..60}
           do
             echo "Request $i to the URL..."
@@ -164,10 +167,12 @@ jobs:
             echo "Did not receive a 200 response, sleeping for 0.5 second..."
             sleep 0.5
           done
+          set -e  # enable exit on error
           echo "Timed out after 30 seconds, step failed."
           exit 1
       - name: Wait for Sample3 to spin up
         run: |
+          set +e  # disable exit on error
           for i in {1..60}
           do
             echo "Request $i to the URL..."
@@ -179,10 +184,12 @@ jobs:
             echo "Did not receive a 200 response, sleeping for 0.5 second..."
             sleep 0.5
           done
+          set -e  # enable exit on error
           echo "Timed out after 30 seconds, step failed."
           exit 1
       - name: Wait for Sample4 to spin up
         run: |
+          set +e  # disable exit on error
           for i in {1..60}
           do
             echo "Request $i to the URL..."
@@ -194,6 +201,7 @@ jobs:
             echo "Did not receive a 200 response, sleeping for 0.5 second..."
             sleep 0.5
           done
+          set -e  # enable exit on error
           echo "Timed out after 30 seconds, step failed."
           exit 1
       - name: Build supergraph with federation-${{ matrix.federationversion }}-supergraph-config.yaml
