Update

diff --git a/.github/workflows/test-code.yml b/.github/workflows/test-code.yml
--- a/.github/workflows/test-code.yml
+++ b/.github/workflows/test-code.yml
@@ -103,15 +103,51 @@ jobs:
       - name: Build solution [Debug]
         working-directory: src
         run: dotnet build --no-restore -c Debug
+      - name: Start Sample1 on port 5601
+        working-directory: src
+        run: dotnet run --no-build --project GraphQL.Federation.Server1 &
+      - name: Start Sample2 on port 5602
+        working-directory: src
+        run: dotnet run --no-build --project GraphQL.Federation.Server2 &
       - name: Install Apollo Rover CLI
         run: |
           curl -sSL https://rover.apollo.dev/nix/latest | sh
           echo "/home/runner/.rover/bin" >> $GITHUB_PATH
-      - name: Test rover
-        run: |
-          rover config --help
           rover --version
-          rover
+      - name: Wait for Sample1 to spin up
+        run: |
+          for i in {1..60}
+          do
+            echo "Request $i to the URL..."
+            response=$(curl -s -o /dev/null -I -w "%{http_code}" http://localhost:5601)
+            if [ $response -eq 200 ]; then
+              echo "Received 200 response, step completed."
+              exit 0
+            fi
+            echo "Did not receive a 200 response, sleeping for 0.5 second..."
+            sleep 0.5
+          done
+          echo "Timed out after 30 seconds, step failed."
+          exit 1
+      - name: Wait for Sample2 to spin up
+        run: |
+          for i in {1..60}
+          do
+            echo "Request $i to the URL..."
+            response=$(curl -s -o /dev/null -I -w "%{http_code}" http://localhost:5602)
+            if [ $response -eq 200 ]; then
+              echo "Received 200 response, step completed."
+              exit 0
+            fi
+            echo "Did not receive a 200 response, sleeping for 0.5 second..."
+            sleep 0.5
+          done
+          echo "Timed out after 30 seconds, step failed."
+          exit 1
+      - name: Build supergraph
+        working-directory: src
+        run: |
+          rover supergraph compose --config ./federation-supergraph-config.yaml
   buildcheck:
     needs:
       - test
